\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{gpr-report}[2022/11/21 v1.0.0 Report class for the Grundpraktikum Physik at the Carl-von-Ossietzky University Oldenburg]

% Packages required to use this class successfully
\RequirePackage[left=1.75cm,right=1.75cm,top=1.75cm,bottom=2cm,footskip=15pt]{geometry}
\RequirePackage{lmodern}
\RequirePackage{amsmath,amssymb,amsfonts,amsthm}
\RequirePackage{mathtools}
\RequirePackage{fancyhdr}
\RequirePackage{titling}
\RequirePackage{subcaption}
\RequirePackage{graphicx}
\RequirePackage{float}
\RequirePackage[bottom]{footmisc}
\RequirePackage[useregional]{datetime2}
\RequirePackage[pdfusetitle]{hyperref}
\RequirePackage{listings}
\RequirePackage[hypcap=true]{caption}
\RequirePackage{pdfpages}
\RequirePackage{siunitx}
\RequirePackage{setspace}
\RequirePackage{esdiff}
\RequirePackage{tcolorbox}
